// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvdmbkhmqbgwcryqzbfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2ZG1ia2htcWJnd2NyeXF6YmZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNzYyNzUsImV4cCI6MjA2Nzc1MjI3NX0.Z4Dt9D0HhZXsIZQCwdC60vBsmKtfusYSWprsELKRe6g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});